### ISSUE TITLE
Market Metrics

### ISSUE THREAD

**Issue by GeorgLink** [Bugmark-Simulator/bugmark_simulation#10]
- [x] Determine which metrics about the market should be shown to 'market metrics' and 'both metrics' treatments.
- [x] Implement market metrics
  - [x] Contract Fix Rate
  - [x] Payout vs Potential
  - [x] Variance of Offer volumes
  - [x] Open Offer count and volume
  - [x] Maturation days table

**Comment by GeorgLink** [comment]
This might have to wait for two weeks, until Malvika is back

**Comment by GeorgLink** [comment]
Changing title because we now 'determined market metrics'. 

I'm documenting visualization ideas here but they are open to discussion and ideas.


1. **Contract Fix Rate** -- a graph with 0-100% on y-axis and days on x-axis, shows the percentage of contracts that are each day resolved to pay out fixed side owners. Because these values are independent, we might have to display dots or columns for the individual days but add a 5 day trailing average line. 

2. **Payout vs Potential** -- a graph with tokens on the y-axis and days on the x-axis, shows for contracts maturing each day, how much was paid out to fixed side and what the total contract volume was.  This graph can even go into the future, showing contract volume in upcoming days without realized payouts. We might want to add overall potential from all offers that could have resulted in contracts to mature at day X. In addition to daily values, we might display a 5 day trailing average line.

3. **Variance of Offer volumes** -- a graph with tokens on the y-axis and days on the x-axis. For each day, show the maximum, average, and minimum offer volume*price. Again, trailing average line.

4. **Open Offer count and volume** -- a graph with tokens the left y-axis, a count on the right y-axis, and days on the x-axis, show number of offers to mature on a day and total volume of offers. Again, trailing average line.

5. **Maturation days table** -- a table with columns: day (future only), last price, price change, high-price, low-price, volume, last contract cross time (in seconds)

**Comment by dmarti** [comment]
Total volume for Bugmark as a whole?

**Comment by GeorgLink** [comment]
Thanks @dmarti. Total volume for Bugmark is a good idea but not helpful for people to choose between projects. Maybe we can put it on the 'researcher dashboard' as an overview of the total simulation.

**Comment by snehasi** [comment]
Thanks @GeorgLink for the detailed description. Could you assign it to me, as I am already working on it?

**Comment by GeorgLink** [comment]
Yes, I will do that. Can you please share your progress frequently? Maybe you can start a pull request and keep updating it. Let me know if you need help figuring out our simulation platform.

**Comment by GeorgLink** [comment]
I can only add you after you accept the invite to be a member of this repository.

**Comment by snehasi** [comment]
Great. Sure!

**Comment by vinodahujauno** [comment]
SQL for maturation days table
In this sql Project variable is defined in grafana
```sql
select co.maturation,   
(select price from positions
join amendments
on positions.amendment_uuid = amendments.uuid
join contracts as ci
on amendments.contract_uuid = ci.uuid
join issues
on ci.stm_issue_uuid=issues.uuid
where positions.side = 'unfixed'
and issues.stm_tracker_uuid = '[[project]]'
and ci.maturation = co.maturation
order by positions.updated_at DESC limit 1) as LastPrice, max(positions.price) as HighPrice, min(positions.price) as LowPrice, sum(positions.volume) as Volume
from positions
join amendments
on positions.amendment_uuid = amendments.uuid
join contracts as co
on amendments.contract_uuid = co.uuid
join issues
on co.stm_issue_uuid=issues.uuid
where positions.side = 'unfixed'
and issues.stm_tracker_uuid = '[[project]]'
and co.status = 'open'
group by co.maturation
order by co.maturation
;

```

**Comment by vinodahujauno** [comment]
Done
