### ISSUE TITLE
Issue generation script

### ISSUE THREAD

**Issue by GeorgLink** [Bugmark-Simulator/bugmark_simulation#18]
The issue generation script requires 2 parts: 

1. A settings file
2. A script to generate issues

The issue script will be run as a cron job, as part of the simulation, or can be called manually.

The settings file may be a YAML file that contains information about:
- how many issues per tracker = 10
- required skills = see below
- setting for how many skills each issue gets = 3

To begin, we can have the following skills:
- Java
- Ruby
- Phython
- HTML/CSS
- C++
- Go

**Comment by vinodahujauno** [comment]
Done
