### ISSUE TITLE
Nightly Script

### ISSUE THREAD

**Issue by vinodahujauno** [Bugmark-Simulator/bugmark_simulation#19]
Write a nightly script:
# Runs every x minutes
 - advance simulation day +1
 - (if issue tracker is not synced, sync)
 - resolved matured contracts
 - expire expired offers
- (each step needs to update the user balances)
- generate new issues

**Comment by GeorgLink** [comment]
# Runs every x minutes
 - advance simulation day +1
   * (Location of BugmTime class and its functions  `/home/vahuja/src/exchange/app/libs/`)
```ruby
    BugmTime.go_past_end_of_day
```
 - (if issue tracker is not synced, sync)
 - resolved matured contracts
```ruby
    Contract.pending_resolution.each do |contract|
       ContractCmd::Resolve.new(contract).project
    end
```
 - expire expired offers
```ruby
Offer.open.expired_by_time.each do |offer|
  offer.update_attribute(:status, 'expired')
end
```
- (each step needs to update the user balances)
  * Already in resolved mature contracts.
 - generate new issues
  - Look at the detail of generate new issues: #18 

( optional optimization step - update project health metrics to reduce queries)

**Comment by vinodahujauno** [comment]
Done. 

@GeorgLink please review

**Comment by GeorgLink** [comment]
Can you post a link to the file or reference to a pull request for me to review?

**Comment by vinodahujauno** [comment]
https://github.com/Bugmark-Simulator/bugmark_simulation/blob/master/exercise/simulation/script/nightly_scr

On Thu, Jul 19, 2018 at 8:47 AM, Georg J.P. Link <notifications@github.com>
wrote:

> Can you post a link to the file or reference to a pull request for me to
> review?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_Bugmark-2DSimulator_bugmark-5Fsimulation_issues_19-23issuecomment-2D406281939&d=DwMCaQ&c=Cu5g146wZdoqVuKpTNsYHeFX_rg6kWhlkLF8Eft-wwo&r=uuEPpUZhZPku7npCczAKiv8Rovz29zAuhtZXL3gDsks&m=MZbskXPvSC5HYSg1zVZkOyBPlsfp9BTwBlFClmUKLkk&s=r72JROHkJPhUYbmpucCjemqBJN2ypSPZigsrpgHttD4&e=>,
> or mute the thread
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_AYSdU4pjA4nNqHU8o-5F9U9Wg0WwF1fQReks5uII3ogaJpZM4U0c2d&d=DwMCaQ&c=Cu5g146wZdoqVuKpTNsYHeFX_rg6kWhlkLF8Eft-wwo&r=uuEPpUZhZPku7npCczAKiv8Rovz29zAuhtZXL3gDsks&m=MZbskXPvSC5HYSg1zVZkOyBPlsfp9BTwBlFClmUKLkk&s=dyCI414m0UocWZ620OV9n8D7PJPfCs0QJVekEjQ-1Z4&e=>
> .
>



-- 
*Vinod Kumar Ahuja*
Graduate Assistant | Management Information Systems | UNO
Vice President | Management Information Systems Student Organization (MISSO)

Ph: 531-205-8338 | E-mail: vahuja@unomaha.edu

**Comment by GeorgLink** [comment]
Thanks. Script looks good. 

We talked about 'pausing' the simulation and re-adjusting the BugmTime when we start the simulation again. Is that implemented yet?

**Comment by vinodahujauno** [comment]
No not yet. Need to discuss in person some options on that.

**Comment by GeorgLink** [comment]
Okay

**Comment by GeorgLink** [comment]
I'm happy with the nightly script as is. Any other modifications will get their own issues.
