### ISSUE TITLE
Simulation Pace Control

### ISSUE THREAD

**Issue by GeorgLink** [Bugmark-Simulator/bugmark_simulation#2]
- [x] Display at top of every page: current simulation day and time until next day
- [x] Cronjob that automate advancing simulation day
- [ ] On researcher dashboard: setting for pace of simulation (time between days)

**Comment by vinodahujauno** [comment]
All done except researcher dashboard settings. Instead of the researcher dashboard, all the setting are defined in setting YAML files.

**Comment by GeorgLink** [comment]
What is the location of the settings file?

Does it combine all settings that we could make across the entire
simulation platform?
​

**Comment by vinodahujauno** [comment]
location of all the settings file is in the script folder.

Each script has separate settings file. But we can combine them in one
settings file. It is just that we have to redefine our variables in the
script to access it from one setting file.


On Thu, Jul 19, 2018 at 8:48 AM, Georg J.P. Link <notifications@github.com>
wrote:

> What is the location of the settings file?
>
> Does it combine all settings that we could make across the entire
> simulation platform?
> ​
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_Bugmark-2DSimulator_bugmark-5Fsimulation_issues_2-23issuecomment-2D406282423&d=DwMFaQ&c=Cu5g146wZdoqVuKpTNsYHeFX_rg6kWhlkLF8Eft-wwo&r=uuEPpUZhZPku7npCczAKiv8Rovz29zAuhtZXL3gDsks&m=ys5Lk8B_QUN_t6xjdLyMRLkET6_zuVHrJhWX__CrWsg&s=LcA8QwyJvukcXKbdomdQoagpMKN3scnN0njBgw3IC6M&e=>,
> or mute the thread
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_AYSdUyJR5XWDjdPFrY1eTpKq0Kqa-2D7P7ks5uII49gaJpZM4Uoftl&d=DwMFaQ&c=Cu5g146wZdoqVuKpTNsYHeFX_rg6kWhlkLF8Eft-wwo&r=uuEPpUZhZPku7npCczAKiv8Rovz29zAuhtZXL3gDsks&m=ys5Lk8B_QUN_t6xjdLyMRLkET6_zuVHrJhWX__CrWsg&s=9eEfLeJy-03pkpYJZDqVF9kXSV8h5egJimLMAsCDUH8&e=>
> .
>



-- 
*Vinod Kumar Ahuja*
Graduate Assistant | Management Information Systems | UNO
Vice President | Management Information Systems Student Organization (MISSO)

Ph: 531-205-8338 | E-mail: vahuja@unomaha.edu

**Comment by GeorgLink** [comment]
​I like the idea of having one master setting file, it will make it easier
for someone new to the program to know where to adjust things. Can you
please create an issue to combine settings at some point?

**Comment by GeorgLink** [comment]
Pace can be controlled in a settings file; 
Simulation can be started and stopped within the admin dashboard
