### ISSUE TITLE
Transfer repository to GitHub Organization: Bugmark-Simulator

### ISSUE THREAD

**Issue by GeorgLink** [Bugmark-Simulator/bugmark_simulation#22]
Transfer repository to GitHub Organization: https://github.com/Bugmark-Simulator

@vinodahujauno I sent you an invite.

I would like to have a clean GitHub Organization that is only for this research project. No other repositories. This will allow us to clean our GitHub accounts, without having to remove the repositories from the internet or changing urls later.

**Comment by vinodahujauno** [comment]
Done.

**Comment by GeorgLink** [comment]
https://help.github.com/articles/transferring-a-repository-owned-by-your-personal-account/

It did not seem to work, the issue tracker did not get moved. Did you follow the steps described in the help pages?

**Comment by vinodahujauno** [comment]
No, that page was not provided earlier and I have no clue of what this option exists. I just opened a repo and commit all the code from the Linode server over there.

We can delete the repo and follow the transfer steps.

**Comment by GeorgLink** [comment]
​Okay, no problem.

**Comment by vinodahujauno** [comment]
Done.
