### ISSUE TITLE
Skills and difficulties

### ISSUE THREAD

**Issue by GeorgLink** [Bugmark-Simulator/bugmark_simulation#3]
- [x] A user needs to be assigned skill of different levels
- [ ] An issue needs different required skills with different difficulty levels

**Comment by vinodahujauno** [comment]
@GeorgLink A user needs to be assigned skill of different levels. Done is user generation script

**Comment by vinodahujauno** [comment]
@GeorgLink I have ignored skill level for the user but what about skill levels for issues. Do we need to have skill levels for issues or not.

**Comment by GeorgLink** [comment]
No, let's ignore skill levels everywhere.
​

**Comment by vinodahujauno** [comment]
Done
