### ISSUE TITLE
chartkick is currently not installed as part of the install instructions

### ISSUE THREAD

**Issue by GeorgLink** [Bugmark-Simulator/bugmark_simulation#36]
I followed the installation instructions and built a new VM from scratch. 

I fail with not having chartkick installed as part of the process. We need to add a step somewhere in the instructions or add chartkick as part of one of the automated processes that we call.

**Comment by GeorgLink** [comment]
I know we did not want to alter the exchange .... but the easiest was to include chartkick in the exchange's Gemfile:

https://github.com/Bugmark-Simulator/exchange/commit/e8699d185f697a31c2f53c7cd9212d4fada57932

Solved!

**Comment by vinodahujauno** [comment]
I think we agreed on dygrap for charting instead of chartkick and we saved dygrap.js and dygraph.css files so no need of changing the exchange.

**Comment by GeorgLink** [comment]
I received an error that chartkick was missing... it is must be used
somewhere in the simulator's code.
