### ISSUE TITLE
Move duration of tasks to settings file

### ISSUE THREAD

**Issue by GeorgLink** [Bugmark-Simulator/bugmark_simulation#38]
righ tnow the duration of a task is hard coded in the app_helper file 

```ruby
  sql = "INSERT INTO work_queues (user_uuid, issue_uuid, task, added_queue, position, completed, startwork)
  values ('#{user_uuid}','#{issue_uuid}','#{task}',
    '#{BugmTime.now.to_s.slice(0..18)}', 1, #{startdate} + '10 seconds',#{startdate}) ;"
```

**Comment by vinodahujauno** [comment]
which setting file u want it to move.  In this file '../../Base/lib/trial_settings' or any other file.

**Comment by GeorgLink** [comment]
~/trial/simulation/settings/Settings.yml

**Comment by GeorgLink** [comment]
That way, the settings will be available from the `TS` object, like all
other settings.

**Comment by GeorgLink** [comment]
done
