### ISSUE TITLE
Ability to do work

### ISSUE THREAD

**Issue by GeorgLink** [Bugmark-Simulator/bugmark_simulation#4]
- [x] Display on issue detail page about progress of work, option to do and cancel work
- [x] Sortable queue on user dashboard showing what issue is being worked on and which issues are next
- [x] As time advances, work needs to be completed automatically

**Comment by vinodahujauno** [comment]
Reference:
https://infinum.co/the-capsized-eight/progress-bar-in-rails

**Comment by vinodahujauno** [comment]
Work Queue Done
