### ISSUE TITLE
Update Dates in Issue Table

### ISSUE THREAD

**Issue by vinodahujauno** [Bugmark-Simulator/bugmark_simulation#64]
Update dates (i.e. First Activity and Last Activity) in json field of issues table.

Update will be when a comment is passed or a work is done or issue is closed.

**Comment by GeorgLink** [comment]
completed?

**Comment by GeorgLink** [comment]
It would be a matter of determining at which points we need to update the
dates and checking the code that we hit all of the spots.

Here are my initial thoughts, please add anything:

- [ ] When issue is created
- [ ] When issue is closed
- [ ] When user makes a comment
- [ ] When user decides to work on an issue
- [ ] When ... ?

**Comment by GeorgLink** [comment]
I think it's complete.
