### ISSUE TITLE
Modify Issue Page

### ISSUE THREAD

**Issue by vinodahujauno** [Bugmark-Simulator/bugmark_simulation#8]
Add Following:
1. Project Name
2. Percentage Complete
3. Skills required.
4. History --> #12 
5. Comments --> #13

**Comment by vinodahujauno** [comment]
@GeorgLink  How  do you want to generate issue. Should I create a page similar to user generation I developed whereby we add issues in the system. Something like this:

http://173.230.144.39:4567/account_creation

**Comment by GeorgLink** [comment]
#18 is a new issue with that details issue generation.

We can create an admin page, but that is low priority. Issue generation can be a script that runs in the background.

**Comment by vinodahujauno** [comment]
Added skills required for issues. 
@GeorgLink please review on 
http://173.230.144.39:4567

**Comment by GeorgLink** [comment]
I don't see it.
​

**Comment by vinodahujauno** [comment]
On the issue list page under skill, you will see java and that data is extracted from jfeilds of issue table.

**Comment by GeorgLink** [comment]
Ah, okay. Since each row showed 'Java', it was not clear that it was from
the database. I found it in the source file.

Thanks!​
