### ISSUE TITLE
Health Metrics 

### ISSUE THREAD

**Issue by GeorgLink** [Bugmark-Simulator/bugmark_simulation#9]
- [x] (Open Issues) | What is the number of open issues?
- [x] Closed Issues | What is the number of closed issues?
- [x] Issue Resolution Efficiency | What is the number of closed issues/number of abandoned issues?
- [x] Open Issue Age | What is the the age of open issues?
- [x] First Response Days | What is the duration of time for a first response to an issue?
- [x] Issue Resolution Days (last 100 issues)

Metric | Question
-- | --
(Open Issues) | What is the number of open issues?
Closed Issues | What is the number of closed issues?
Issue Resolution Efficiency | What is the number of closed issues/number of abandoned issues?
Open Issue Age | What is the the age of open issues?
First Response Days | What is the duration of time for a first response to an issue?
Issue Resolution Days | What is the duration of time for the **last 100** issues to be resolved?

**Comment by snehasi** [comment]
Hi @GeorgLink, most of these have been covered in this PR : https://github.com/GeorgLink/bmx-bot/pull/23 , as visualization for the bmx-bot. Maybe, we can use those charts for generating the market metrics here?

**Comment by GeorgLink** [comment]
@snehasi thank you for pointing this out.  -- @vinodahujauno can you please see if you want to use Sneha's solution?
